let nothing = false;
let frågorochsvar = {
  "Jungen": "pojkar",
  "gelb": "gul",
  "böse": "arg",
  "müde": "trött",
  "höflich": "hövlig",
  "durstig": "törstig",
  "Schumacher": "skomakare",
  "Urlaub": "semester",
  "hübsch": "vacker",
  "Ecke": "hörn",
  "wahr": "sann",
  "Pferd": "häst",
  "Zeit": "tid",
  "Angst": "rädsla",
  "Krank": "sjuk",
  "alt": "gammal",
  "bäcker": "bagare",
  "Tier": "djur",
  "Haar": "hår",
  "Geld": "pengar",
  "erzählen": "berätta",
  "glücklich": "lycklig",
  "beweis": "bevis",
  "schrecklich": "hemsk",
  "teuer": "dyr"
}
