let nothing = true;
let frågorochsvar = {
    "eins": "ett",
    "zwei": "två",
    "drei": "tre",
    "vier": "fyra",
    "fünf": "fem",
    "sechs":"sex",
    "sieben": "sju",
    "acht": "åtta",
    "neun": "nio",
    "zehn": "tio",
    "elf": "elva",
    "zwölf": "tolv",
    "dreizehn": "tretton",
    "neunzehn": "nitton",
    "zwanzig": "tjugo",
    "dreizig": "trettio",
    "vierzig": "fyrtio",
    "fünfzig": "femtio",
    "sechzig": "sextio",
    "achtzig": "åttio",
    "neunzig": "nittio",
    "einhundert": "etthundra",
    "Wann": "När",
    "Wie": "Hur/Vad",
    "Wo": "Var",
    "Woher": "Varifrån",
    "Wer": "Vem",
    "Warum": "Varför",
    "Was": "Vad",
    "Wie viel": "Hur mycket",
    "Wie viele": "Hur många",
    "Wie spät ist es": "Hur mycket är klockan",
    "Wie viel Uhr ist es": "Hur mycket är klockan",
    "Es ist ein Uhr": "Den är ett",
    "Es ist Viertel nach": "Den är kvart över",
    "Es ist Viertel vor": "Den är kvart i",
    "Es ist halb": "Den är halv",
    "Um sieben Uhr": "Klockan sju",
    "Um halb acht": "Klockan halv åtta",
    "die Stunde": "timmen",
    "die Minute": "minuten",
    "die Schule": "skolan",
    "die Hausaufgabe": "läxan",
    "der Unterricht": "undervisningen",
    "die Pause": "rasten",
    "das Lieblingsfach": "favoritämnet",
    "Mathematik": "matte",
    "Schwedisch": "svenska",
    "Deutsch": "tyska",
    "Englisch": "engelska",
    "Französich": "franska",
    "Spanisch": "spanska",
    "Geschichte": "historia",
    "Erdkunde": "geografi",
    "Sport": "idrott",
    "Musik": "musik",
    "Kunst": "bild",
    "die Stunde": "lektionen",
    "der Schulhof": "skolgården",
    "der Stundenplan": "schemat",
    "Ich gehe in Klasse 7D": "Jag går i klass 7D",
    "die Parallelklasse": "Parallellklassen",
    "Wie viele Stunden": "Hur många lektioner",
    "Montag": "måndag",
    "Dienstag": "tisdag",
    "Mittwoch": "onsdag",
    "Donnerstag": "torsdag",
    "Freitag": "fredag",
    "samstag/sonnabend": "lördag",
    "sonntag": "söndag",
}